name: fstrinkets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: |
        sudo apt --only-upgrade install g++-10 cmake
        sudo apt install libudev-dev

    - name: Build
      run: |
        mkdir out
        cd out
        export CC=/usr/bin/gcc-10
        export CXX=/usr/bin/g++-10
        cmake ..
        make
